
import java.util.Scanner;

//Create ConvertStringToUpperCase to convert the string to Uppercase
public class ConvertStringToUpperCase{
    
     //Create a method that using charAt() method to check the string are equal or not
    public boolean compareStringsUsingCharAt(String str1, String str2){

        //Check the length of string if different return false
        if(str1.length() != str2.length()){
            return false;
        }

        //Take a loop that compare string using charAt method
        for(int i=0;i<str1.length();i++){
            if(str1.charAt(i) != str2.charAt(i)){
                return false; // if we found the different char at same index return false
            }
        }
        return true;//at the end return true
    }

    //Create a method that use charAt method to convert the string to upperCase
    public String convertUpperCase(String str){

        //Create a new Str variable and assign to "";
        String newStr = "";
    
        //Take a loop that compare string using charAt method to convert string to uppercase
        for(int i=0;i<str.length();i++){

            //Create a variable and store the ascii value of character
            int asciiValue = str.charAt(i);

            //If the ascii is between the 97 and 122 then subtract 32 to convert into lowercase
            if(asciiValue >= 97 && asciiValue <= 122){
                newStr = newStr + (char)(asciiValue - 32);
            }else{
                //else simply add to string
                newStr = newStr + (char)(asciiValue);
            }
        }
        return newStr;//return the newStr
    }

    public static void main(String[] agrs){

        //Create the object of the the class ConvertStringToUpperCase
        ConvertStringToUpperCase ConvertStringToUpperCase = new ConvertStringToUpperCase();

        // Create a Scanner object to take user input
        Scanner input = new Scanner(System.in);

        // Ask for the string input
        System.out.print("Enter the string: ");
        String str = input.nextLine();


        //Create a variable str1 that store the string that return by toUpperCase inbuilt method
        String str1 = str.toUpperCase();

        //Create a variable str2 that store the result that return by convertUpperCase method
        String str2 = ConvertStringToUpperCase.convertUpperCase(str);

        //Create a variable isEqual that store the result that return by compareStringsUsingCharAt method
        boolean isEqual = ConvertStringToUpperCase.compareStringsUsingCharAt(str1, str2);

        //print the result
        if(isEqual){
            System.out.println("Both String are equal");
        }else{
            System.out.println("Both String are not equal");
        }

        //print the result
        System.out.println("String generated by inbuilt method: " + str1);
        System.out.println("String generated by user defined method: " + str2);

        // Close the scanner to prevent resource leak
        input.close();

    }
}